### ISSUE TITLE
What are Aliases?

### ISSUE THREAD

**Issue by mcmikemn** [marverix/gah#1]
The README says "Has own base of predefined aliases for GitHub repositories". I'm not finding any aliases. I also didn't find Github Discussions or a link to a Matrix room or anything, so I'm hoping here might be a place to ask about `gah`. What/where are the aliases and how do I use them?

Thanks.

**Comment by bryanniwa** [comment]
Aliases are just a list of hardcoded repos where you don't need to specify the entire repo path when installing. For example, you can run `gah install bat` instead of `gah install sharkdp/bat`. Running `gah show aliases` prints the list of defined aliases

**Comment by mcmikemn** [comment]
Aha! 

`gah help` says:
```
gah
  ...
  show <aliases>
  ...
```
So I tried `gah show` and `gah show bat` but didn't realize that "\<aliases\>" meant to literally type "alias".

Thanks.

**Comment by bryanniwa** [comment]
Ah yeah I think it's suggesting that they may add more options there in the future
